// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA6Dx4BQAW7XDUNJxVb4BMNLEF0vZCwxM',
    appId: '1:623479456400:web:bfc4e0a196c0bef7e40e15',
    messagingSenderId: '623479456400',
    projectId: 'instagram-6c24b',
    authDomain: 'instagram-6c24b.firebaseapp.com',
    storageBucket: 'instagram-6c24b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtUgLRYz4mBXvnJskSHuABcv8EHenGqwk',
    appId: '1:623479456400:android:180487af7bd47a2de40e15',
    messagingSenderId: '623479456400',
    projectId: 'instagram-6c24b',
    storageBucket: 'instagram-6c24b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDScBYqOWGCkllbr3jg6RmvfMYFRzj7LJk',
    appId: '1:623479456400:ios:40ea0c94b931afbee40e15',
    messagingSenderId: '623479456400',
    projectId: 'instagram-6c24b',
    storageBucket: 'instagram-6c24b.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );
}
